
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Backend.Analizadores;

/** CUP generated class containing symbol constants. */
public class parser_FigurasSym {
  /* terminals */
  public static final int LINEA = 7;
  public static final int ANIMACION = 2;
  public static final int RES = 15;
  public static final int CIER = 19;
  public static final int SUM = 14;
  public static final int ANIMAR = 10;
  public static final int COLOR = 3;
  public static final int CUADRADO = 5;
  public static final int OBJETO = 11;
  public static final int GRAFICAR = 9;
  public static final int COMA = 20;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int DIV = 17;
  public static final int APER = 18;
  public static final int error = 1;
  public static final int NUMERO = 13;
  public static final int POLIGONO = 8;
  public static final int CIRCULO = 4;
  public static final int ANTERIOR = 12;
  public static final int RECTANGULO = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ANIMACION",
  "COLOR",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "LINEA",
  "POLIGONO",
  "GRAFICAR",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "NUMERO",
  "SUM",
  "RES",
  "MULT",
  "DIV",
  "APER",
  "CIER",
  "COMA"
  };
}

